name: titan_fil
description: "titanEdge."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+110


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convert: ^3.1.2
  dio: ^5.8.0+1
  path: ^1.8.1
  process_run: ^1.2.2
  introduction_screen: ^3.0.0
  file_picker: ^10.1.9
  window_manager: ^0.4.3
#  shared_preferences: ^2.0.15
  shared_preferences: ^2.5.3
  url_launcher: ^6.0.9
  system_tray: ^2.0.3
  logging: ^1.0.2
  path_provider: ^2.0.2
  package_info_plus: ^4.0.0
  archive: ^3.4.10
  win32: any
  ffi: ^2.0.1
  uuid: ^4.4.2
  open_file: ^3.4.0
  dart_ping: ^9.0.1
  get: ^4.6.6
  gif_view: any
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.2.3
  logger: ^2.4.0
  toastification: ^2.3.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.0
  just_the_tooltip: ^0.0.12
  another_flutter_splash_screen: ^1.2.1
  fl_chart: 0.69.2
  toml: ^0.16.0
  google_fonts: ^6.2.1
  calendar_date_picker2: 1.1.9
  intl: 0.19.0
  chinese_font_library: ^1.2.0
  desktop_disk_space: ^0.0.1
  lottie: any
  crypto: ^3.0.3
#  webview_flutter: any

# 强制所有依赖库使用相同的 uuid 版本
dependency_overrides:
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.6
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/l10n/
    - assets/fonts/
    - assets/configs/
    - assets/json/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSansTibetanVF.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  assets:
    enabled: true
